// Bedrock provider + model + API data, distilled from source
window.BEDROCK_DATA = {
  providers: [
    { id: 'amazon',    name: 'Amazon',     sub: 'Nova · Titan',         color: '#4fa3ff', hue: 210 },
    { id: 'anthropic', name: 'Anthropic',  sub: 'Claude',               color: '#a78bfa', hue: 260 },
    { id: 'meta',      name: 'Meta',       sub: 'Llama',                color: '#3ddbb0', hue: 165 },
    { id: 'mistral',   name: 'Mistral AI', sub: 'Mistral · Devstral',   color: '#ffb84d', hue: 36  },
    { id: 'cohere',    name: 'Cohere',     sub: 'Command · Embed',      color: '#ff7a59', hue: 16  },
    { id: 'ai21',      name: 'AI21 Labs',  sub: 'Jamba · Jurassic',     color: '#c7c3b6', hue: 45  },
    { id: 'deepseek',  name: 'DeepSeek',   sub: 'R1 · V3',              color: '#ff5b5b', hue: 0   },
    { id: 'qwen',      name: 'Qwen',       sub: 'Alibaba',              color: '#ff5fa2', hue: 330 },
    { id: 'openai',    name: 'OpenAI',     sub: 'GPT-OSS',              color: '#8fd66a', hue: 100 },
    { id: 'google',    name: 'Google',     sub: 'Gemma',                color: '#5aa9ff', hue: 220 },
    { id: 'nvidia',    name: 'NVIDIA',     sub: 'Nemotron',             color: '#a4e34c', hue: 90  },
    { id: 'stability', name: 'Stability',  sub: 'SD · Image',           color: '#d4a24c', hue: 42  },
    { id: 'writer',    name: 'Writer',     sub: 'Palmyra',              color: '#b8b3a7', hue: 40  },
    { id: 'zai',       name: 'Z AI',       sub: 'GLM (Zhipu)',          color: '#9672ff', hue: 255 },
    { id: 'minimax',   name: 'MiniMax',    sub: 'M series',             color: '#ff68a8', hue: 335 },
    { id: 'moonshot',  name: 'Moonshot',   sub: 'Kimi',                 color: '#2fd4b0', hue: 170 },
    { id: 'luma',      name: 'Luma',       sub: 'Ray video',            color: '#ff4444', hue: 5   },
    { id: 'twelvelabs',name: 'TwelveLabs', sub: 'Video embeddings',     color: '#d4a866', hue: 38  },
  ],
  // kind: chat | reason | vision | speech | embed | image | video | rerank
  models: {
    amazon: [
      { n: 'Nova 2 Lite',        k: 'reason',  flag: '✦', caps: ['T','V','R'] },
      { n: 'Nova Premier',       k: 'chat',    caps: ['T','V'] },
      { n: 'Nova Pro',           k: 'chat',    caps: ['T','V'] },
      { n: 'Nova Lite',          k: 'chat',    caps: ['T','V'] },
      { n: 'Nova Micro',         k: 'chat',    caps: ['T'] },
      { n: 'Titan Text Premier', k: 'chat' },
      { n: 'Titan Text Express', k: 'chat' },
      { n: 'Titan Text Lite',    k: 'chat' },
      { n: 'Titan Text G1 Large',k: 'chat' },
      { n: 'Nova 2 Sonic',       k: 'speech',  flag:'✦', caps:['S'] },
      { n: 'Nova Sonic v1',      k: 'speech',  caps:['S'] },
      { n: 'Nova Multimodal Embed', k: 'embed' },
      { n: 'Titan Text Embed V2',   k: 'embed' },
      { n: 'Titan Text Embed G1',   k: 'embed' },
      { n: 'Titan MM Embed G1',     k: 'embed' },
      { n: 'Amazon Rerank 1.0',     k: 'rerank' },
      { n: 'Nova Canvas',        k: 'image' },
      { n: 'Nova Reel v1:0',     k: 'video' },
      { n: 'Nova Reel v1:1',     k: 'video' },
      { n: 'Titan Image Gen G1 v2', k: 'image' },
    ],
    anthropic: [
      { n: 'Claude Opus 4.6',   k:'chat', caps:['T','V'] },
      { n: 'Claude Sonnet 4.6', k:'chat', caps:['T','V'] },
      { n: 'Claude Opus 4.5',   k:'chat', caps:['T','V'] },
      { n: 'Claude Sonnet 4.5', k:'chat', caps:['T','V'] },
      { n: 'Claude Haiku 4.5',  k:'chat', caps:['T','V'] },
      { n: 'Claude Opus 4.1',   k:'chat', caps:['T','V'] },
      { n: 'Claude Sonnet 4',   k:'chat', caps:['T','V'] },
      { n: 'Claude Sonnet 3.7', k:'reason', caps:['T','V','R'] },
      { n: 'Claude Sonnet 3.5 v2', k:'chat', caps:['T','V'] },
      { n: 'Claude Sonnet 3.5', k:'chat', caps:['T','V'] },
      { n: 'Claude Haiku 3.5',  k:'chat', caps:['T'] },
      { n: 'Claude Haiku 3',    k:'chat', caps:['T','V'] },
      { n: 'Claude Sonnet 3',   k:'chat', caps:['T','V'] },
      { n: 'Claude Opus 3',     k:'chat' },
    ],
    meta: [
      { n:'Llama 4 Maverick 17B', k:'chat', caps:['T','V'] },
      { n:'Llama 4 Scout 17B',    k:'chat', caps:['T','V'] },
      { n:'Llama 3.3 70B',        k:'chat', caps:['T'] },
      { n:'Llama 3.2 90B',        k:'chat', caps:['T','V'] },
      { n:'Llama 3.2 11B',        k:'chat', caps:['V'] },
      { n:'Llama 3.2 3B',         k:'chat' },
      { n:'Llama 3.2 1B',         k:'chat' },
      { n:'Llama 3.1 405B',       k:'chat', caps:['T'] },
      { n:'Llama 3.1 70B',        k:'chat', caps:['T'] },
      { n:'Llama 3.1 8B',         k:'chat', caps:['T'] },
      { n:'Llama 3 70B',          k:'chat' },
      { n:'Llama 3 8B',           k:'chat' },
      { n:'Llama 2 Chat 70B',     k:'chat' },
      { n:'Llama 2 Chat 13B',     k:'chat' },
    ],
    mistral: [
      { n:'Mistral Large 3',       k:'chat', caps:['T'] },
      { n:'Devstral 2 135B',       k:'chat' },
      { n:'Magistral Small 1.2',   k:'chat', caps:['V'] },
      { n:'Ministral 14B 3.0',     k:'chat', caps:['V'] },
      { n:'Ministral 8B 3.0',      k:'chat', caps:['V'] },
      { n:'Ministral 3B 3.0',      k:'chat', caps:['V'] },
      { n:'Pixtral Large 25.02',   k:'chat', caps:['T'] },
      { n:'Mistral Large 24.07',   k:'chat', caps:['T'] },
      { n:'Mistral Large 24.02',   k:'chat', caps:['T'] },
      { n:'Mistral Small 24.02',   k:'chat', caps:['T'] },
      { n:'Mistral 7B',            k:'chat' },
      { n:'Mixtral 8×7B',          k:'chat' },
      { n:'Voxtral Mini 1.0',      k:'speech', caps:['S'] },
      { n:'Voxtral Small 1.0',     k:'speech', caps:['S'] },
    ],
    cohere: [
      { n:'Command R+',      k:'chat', caps:['T'] },
      { n:'Command R',       k:'chat', caps:['T'] },
      { n:'Command',         k:'chat' },
      { n:'Command Light',   k:'chat' },
      { n:'Cohere Embed v4', k:'embed' },
      { n:'Embed English v3',k:'embed' },
      { n:'Embed Multilingual v3', k:'embed' },
      { n:'Cohere Rerank 3.5', k:'rerank' },
    ],
    ai21: [
      { n:'Jamba 1.5 Large', k:'chat', caps:['T'] },
      { n:'Jamba 1.5 Mini',  k:'chat', caps:['T'] },
      { n:'Jurassic-2',      k:'chat' },
    ],
    deepseek: [
      { n:'DeepSeek-R1', k:'reason', caps:['R'] },
      { n:'DeepSeek V3.2', k:'chat' },
      { n:'DeepSeek V3.1', k:'chat' },
    ],
    qwen: [
      { n:'Qwen3 Coder 480B', k:'chat' },
      { n:'Qwen3 Coder Next', k:'chat' },
      { n:'Qwen3 Coder 30B',  k:'chat' },
      { n:'Qwen3 235B A22B 2507', k:'chat' },
      { n:'Qwen3 Next 80B A3B', k:'chat' },
      { n:'Qwen3 32B', k:'chat' },
      { n:'Qwen3 VL 235B A22B', k:'chat', caps:['V'] },
    ],
    openai: [
      { n:'GPT-OSS 120B', k:'chat', caps:['T','★'] },
      { n:'GPT-OSS 20B',  k:'chat', caps:['T','★'] },
      { n:'GPT-OSS Safeguard 120B', k:'chat' },
      { n:'GPT-OSS Safeguard 20B',  k:'chat' },
    ],
    google: [
      { n:'Gemma 3 27B', k:'chat', caps:['V'] },
      { n:'Gemma 3 12B', k:'chat', caps:['V'] },
      { n:'Gemma 3 4B',  k:'chat', caps:['V'] },
    ],
    nvidia: [
      { n:'Nemotron Nano 2 VL', k:'chat', caps:['V'] },
      { n:'Nemotron Nano 2', k:'chat' },
      { n:'Nemotron 3 Nano 30B A3B', k:'chat' },
    ],
    stability: [
      { n:'SD 3.5 Large', k:'image' },
      { n:'Stable Image Core 1.0', k:'image' },
      { n:'Stable Image Style Guide', k:'image' },
      { n:'Stable Image Style Transfer', k:'image' },
      { n:'Stable Image Control Sketch', k:'image' },
      { n:'Stable Image Control Structure', k:'image' },
      { n:'Stable Image Inpaint', k:'image' },
      { n:'Stable Image Erase Object', k:'image' },
      { n:'Stable Image Remove Background', k:'image' },
      { n:'Stable Image Search & Replace', k:'image' },
      { n:'Stable Image Search & Recolor', k:'image' },
      { n:'Stable Image Outpaint', k:'image' },
      { n:'Conservative Upscale', k:'image' },
      { n:'Creative Upscale', k:'image' },
      { n:'Fast Upscale', k:'image' },
    ],
    writer: [
      { n:'Palmyra X5', k:'chat', caps:['T'] },
      { n:'Palmyra X4', k:'chat', caps:['T'] },
    ],
    zai: [
      { n:'GLM 5', k:'reason', caps:['T','R','★'] },
      { n:'GLM 4.7', k:'chat', caps:['T'] },
      { n:'GLM 4.7 Flash', k:'chat' },
    ],
    minimax: [
      { n:'MiniMax M2.5', k:'reason', caps:['R','★'] },
      { n:'MiniMax M2.1', k:'chat' },
      { n:'MiniMax M2',   k:'chat' },
    ],
    moonshot: [
      { n:'Kimi K2.5', k:'chat', caps:['T','V'] },
      { n:'Kimi K2 Thinking', k:'reason', caps:['R'] },
    ],
    luma: [
      { n:'Luma Ray v2', k:'video' },
    ],
    twelvelabs: [
      { n:'TwelveLabs Marengo', k:'embed' },
      { n:'TwelveLabs Pegasus', k:'video' },
    ],
  },
  // 8 inference API surfaces
  apis: [
    { id:'invoke',    name:'InvokeModel',           sub:'Sync · every model',                            color:'#a78bfa' },
    { id:'stream',    name:'InvokeModel Stream',    sub:'SSE streaming · text',                          color:'#c4a0ff' },
    { id:'bidir',     name:'Bidirectional Stream',  sub:'Nova Sonic · speech-to-speech',                 color:'#4fa3ff' },
    { id:'converse',  name:'Converse / Stream',     sub:'Unified schema · tools · multi-turn',           color:'#5fb8ff' },
    { id:'mantle',    name:'Mantle (OpenAI-compat)',sub:'Chat Completions · Responses · Models',         color:'#3ddbb0' },
    { id:'batch',     name:'Batch Inference',       sub:'Async S3 · 50% off',                            color:'#ffb84d' },
    { id:'agents',    name:'Bedrock Agents',        sub:'RAG · Flows · Rerank · OptimizePrompt',         color:'#ff7a59' },
    { id:'agentcore', name:'AgentCore Runtime',     sub:'BYO framework · ARN · OAuth',                   color:'#8fd66a' },
  ],
  // which providers feed into each API surface
  apiProviders: {
    invoke:    ['amazon','anthropic','meta','mistral','cohere','ai21','deepseek','qwen','openai','google','nvidia','stability','writer','zai','minimax','moonshot','luma','twelvelabs'],
    stream:    ['amazon','anthropic','meta','mistral','cohere','ai21','deepseek','qwen','openai','google','nvidia','writer','zai','minimax','moonshot'],
    bidir:     ['amazon'],
    converse:  ['amazon','anthropic','meta','mistral','cohere','ai21','deepseek','writer'],
    mantle:    ['openai','deepseek','qwen','zai','mistral','minimax','moonshot','google','nvidia'],
    batch:     ['amazon','anthropic','meta','mistral','deepseek','qwen','openai','google','nvidia','minimax','moonshot'],
    agents:    ['amazon','anthropic','meta','mistral','cohere','ai21','writer'],
    agentcore: ['amazon','anthropic','meta','mistral','cohere','ai21','deepseek','qwen','openai','google','nvidia','writer','zai','minimax','moonshot'],
  },
  stats: {
    providers: 19,
    models: '100+',
    marketplace: '100+',
    apis: 8,
  }
};
